// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: asmd.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ASMDServiceClient is the client API for ASMDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ASMDServiceClient interface {
	Add(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*ASMResponse, error)
	Sub(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*ASMResponse, error)
	Mul(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*ASMResponse, error)
	Div(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*DivResponse, error)
}

type aSMDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewASMDServiceClient(cc grpc.ClientConnInterface) ASMDServiceClient {
	return &aSMDServiceClient{cc}
}

func (c *aSMDServiceClient) Add(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*ASMResponse, error) {
	out := new(ASMResponse)
	err := c.cc.Invoke(ctx, "/asmd.ASMDService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSMDServiceClient) Sub(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*ASMResponse, error) {
	out := new(ASMResponse)
	err := c.cc.Invoke(ctx, "/asmd.ASMDService/Sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSMDServiceClient) Mul(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*ASMResponse, error) {
	out := new(ASMResponse)
	err := c.cc.Invoke(ctx, "/asmd.ASMDService/Mul", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSMDServiceClient) Div(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*DivResponse, error) {
	out := new(DivResponse)
	err := c.cc.Invoke(ctx, "/asmd.ASMDService/Div", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ASMDServiceServer is the server API for ASMDService service.
// All implementations must embed UnimplementedASMDServiceServer
// for forward compatibility
type ASMDServiceServer interface {
	Add(context.Context, *CalcRequest) (*ASMResponse, error)
	Sub(context.Context, *CalcRequest) (*ASMResponse, error)
	Mul(context.Context, *CalcRequest) (*ASMResponse, error)
	Div(context.Context, *CalcRequest) (*DivResponse, error)
	mustEmbedUnimplementedASMDServiceServer()
}

// UnimplementedASMDServiceServer must be embedded to have forward compatible implementations.
type UnimplementedASMDServiceServer struct {
}

func (UnimplementedASMDServiceServer) Add(context.Context, *CalcRequest) (*ASMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedASMDServiceServer) Sub(context.Context, *CalcRequest) (*ASMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedASMDServiceServer) Mul(context.Context, *CalcRequest) (*ASMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mul not implemented")
}
func (UnimplementedASMDServiceServer) Div(context.Context, *CalcRequest) (*DivResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Div not implemented")
}
func (UnimplementedASMDServiceServer) mustEmbedUnimplementedASMDServiceServer() {}

// UnsafeASMDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ASMDServiceServer will
// result in compilation errors.
type UnsafeASMDServiceServer interface {
	mustEmbedUnimplementedASMDServiceServer()
}

func RegisterASMDServiceServer(s grpc.ServiceRegistrar, srv ASMDServiceServer) {
	s.RegisterService(&ASMDService_ServiceDesc, srv)
}

func _ASMDService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASMDServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asmd.ASMDService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASMDServiceServer).Add(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASMDService_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASMDServiceServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asmd.ASMDService/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASMDServiceServer).Sub(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASMDService_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASMDServiceServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asmd.ASMDService/Mul",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASMDServiceServer).Mul(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASMDService_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASMDServiceServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asmd.ASMDService/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASMDServiceServer).Div(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ASMDService_ServiceDesc is the grpc.ServiceDesc for ASMDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ASMDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asmd.ASMDService",
	HandlerType: (*ASMDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ASMDService_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _ASMDService_Sub_Handler,
		},
		{
			MethodName: "Mul",
			Handler:    _ASMDService_Mul_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _ASMDService_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asmd.proto",
}
