// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: asmd.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Var1 int32 `protobuf:"varint,1,opt,name=var1,proto3" json:"var1,omitempty"`
	Var2 int32 `protobuf:"varint,2,opt,name=var2,proto3" json:"var2,omitempty"`
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_asmd_proto_rawDescGZIP(), []int{0}
}

func (x *CalcRequest) GetVar1() int32 {
	if x != nil {
		return x.Var1
	}
	return 0
}

func (x *CalcRequest) GetVar2() int32 {
	if x != nil {
		return x.Var2
	}
	return 0
}

type ASMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *ASMResponse) Reset() {
	*x = ASMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASMResponse) ProtoMessage() {}

func (x *ASMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASMResponse.ProtoReflect.Descriptor instead.
func (*ASMResponse) Descriptor() ([]byte, []int) {
	return file_asmd_proto_rawDescGZIP(), []int{1}
}

func (x *ASMResponse) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type DivResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val1 int32 `protobuf:"varint,1,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2 int32 `protobuf:"varint,2,opt,name=val2,proto3" json:"val2,omitempty"`
}

func (x *DivResponse) Reset() {
	*x = DivResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivResponse) ProtoMessage() {}

func (x *DivResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivResponse.ProtoReflect.Descriptor instead.
func (*DivResponse) Descriptor() ([]byte, []int) {
	return file_asmd_proto_rawDescGZIP(), []int{2}
}

func (x *DivResponse) GetVal1() int32 {
	if x != nil {
		return x.Val1
	}
	return 0
}

func (x *DivResponse) GetVal2() int32 {
	if x != nil {
		return x.Val2
	}
	return 0
}

var File_asmd_proto protoreflect.FileDescriptor

var file_asmd_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x73,
	0x6d, 0x64, 0x22, 0x35, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x76, 0x61, 0x72, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x72, 0x32, 0x22, 0x1f, 0x0a, 0x0b, 0x41, 0x53, 0x4d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x35, 0x0a, 0x0b, 0x44, 0x69,
	0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x76, 0x61, 0x6c, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x6c,
	0x32, 0x32, 0xc1, 0x01, 0x0a, 0x0b, 0x41, 0x53, 0x4d, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2b, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e,
	0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x73,
	0x6d, 0x64, 0x2e, 0x41, 0x53, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b,
	0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x43, 0x61, 0x6c,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e,
	0x41, 0x53, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x4d,
	0x75, 0x6c, 0x12, 0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x41, 0x53, 0x4d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x44, 0x69, 0x76, 0x12,
	0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x44, 0x69, 0x76, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x64, 0x69, 0x70, 0x74, 0x6f, 0x2d, 0x30, 0x30, 0x33, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x70, 0x2f, 0x65, 0x78, 0x70, 0x75, 0x6e, 0x61, 0x72,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asmd_proto_rawDescOnce sync.Once
	file_asmd_proto_rawDescData = file_asmd_proto_rawDesc
)

func file_asmd_proto_rawDescGZIP() []byte {
	file_asmd_proto_rawDescOnce.Do(func() {
		file_asmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_asmd_proto_rawDescData)
	})
	return file_asmd_proto_rawDescData
}

var file_asmd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_asmd_proto_goTypes = []interface{}{
	(*CalcRequest)(nil), // 0: asmd.CalcRequest
	(*ASMResponse)(nil), // 1: asmd.ASMResponse
	(*DivResponse)(nil), // 2: asmd.DivResponse
}
var file_asmd_proto_depIdxs = []int32{
	0, // 0: asmd.ASMDService.Add:input_type -> asmd.CalcRequest
	0, // 1: asmd.ASMDService.Sub:input_type -> asmd.CalcRequest
	0, // 2: asmd.ASMDService.Mul:input_type -> asmd.CalcRequest
	0, // 3: asmd.ASMDService.Div:input_type -> asmd.CalcRequest
	1, // 4: asmd.ASMDService.Add:output_type -> asmd.ASMResponse
	1, // 5: asmd.ASMDService.Sub:output_type -> asmd.ASMResponse
	1, // 6: asmd.ASMDService.Mul:output_type -> asmd.ASMResponse
	2, // 7: asmd.ASMDService.Div:output_type -> asmd.DivResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asmd_proto_init() }
func file_asmd_proto_init() {
	if File_asmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asmd_proto_goTypes,
		DependencyIndexes: file_asmd_proto_depIdxs,
		MessageInfos:      file_asmd_proto_msgTypes,
	}.Build()
	File_asmd_proto = out.File
	file_asmd_proto_rawDesc = nil
	file_asmd_proto_goTypes = nil
	file_asmd_proto_depIdxs = nil
}
